version: '3.8'

services:
  db:
    image: postgres:17.2
    container_name: papertest_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=papertest_db
    volumes:
      - ./postgres:/var/lib/postgresql/data